dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.1

env:
  - VERSION=HEAD ORCA_FIXTURE_FLAGS='--dev --sut-only' ORCA_TEST_FLAGS=--sut-only
  - VERSION=1.0.0-rc1 ORCA_FIXTURE_FLAGS='--dev --sut-only' ORCA_TEST_FLAGS=--sut-only
  - VERSION=1.0.0-rc1
  - VERSION=1.0.0-rc1 ORCA_FIXTURE_FLAGS=--dev

matrix:
  fast_finish: true
  allow_failures:
    - env: VERSION=1.0.0-rc1
    - env: VERSION=1.0.0-rc1 ORCA_FIXTURE_FLAGS=--dev

addons:
  chrome: stable

before_install:
  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - export ORCA=$TRAVIS_BUILD_DIR/../orca
  - export ORCA_FIXTURE=$ORCA-build
  - export ORCA_SUT_NAME=drupal/lightning_api
  - export ORCA_SUT_BRANCH=8.x-4.x
  - export ORCA_PACKAGES_CONFIG_ALTER=../lightning-api/tests/packages.yml

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

  # Install ORCA and prepare the environment.
  - git clone --branch develop --depth 1 https://github.com/acquia/orca.git $ORCA
  - $ORCA/bin/travis/before_install.sh

install:
  - $ORCA/bin/travis/install.sh

  # Run ORCA static analysis tools.
  - orca static-analysis:run ./

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT_NAME --core 8.7.x-dev $ORCA_FIXTURE_FLAGS

before_script:
  - cd $ORCA_FIXTURE/docroot
  - $TRAVIS_BUILD_DIR/update.sh $VERSION

script:
  - orca tests:run --sut $ORCA_SUT_NAME $ORCA_TEST_FLAGS

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
