dist: trusty
language: php

cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - '7.1'

env:
  - VERSION=HEAD

addons:
  chrome: stable

before_install:
  - composer self-update
  - composer --version
  - google-chrome-stable --version

  - export ORCA=$TRAVIS_BUILD_DIR/../orca
  - export ORCA_FIXTURE=$ORCA-build
  - export ORCA_SUT_NAME=drupal/lightning_layout
  - export ORCA_SUT_BRANCH=8.x-2.x
  - export ORCA_PACKAGES_CONFIG_ALTER=../lightning-layout/tests/packages.yml

  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export PATH="$ORCA/bin:$PATH"
  - export PATH="$ORCA/vendor/bin:$PATH"
  - export PATH="$ORCA_FIXTURE/vendor/bin:$PATH"

  # Install ORCA and prepare the environment.
  - git clone --branch develop --depth 1 https://github.com/acquia/orca.git $ORCA
  - $ORCA/bin/travis/before_install.sh

install:
  - $ORCA/bin/travis/install.sh

  # Run ORCA static analysis tools.
  - orca static-analysis:run ./

  # Use ORCA to build the code base.
  - orca fixture:init -f --sut $ORCA_SUT_NAME --core 8.7.x-dev --sut-only

before_script:
  - cd $ORCA_FIXTURE/docroot

script:
  - orca tests:run --sut-only --sut $ORCA_SUT_NAME

after_failure:
  - drush watchdog:show --count=100 --severity=Error --extended
